sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shubham/doker-sample-project -f Dockerfile.dev .

script:
  - docker run -e CI=true shubham/docker-sample-project
