# FROM node:alpine

# WORKDIR '/app'

# COPY package.json .
# RUN npm install

# COPY . .

# CMD ["npm", "run", "start"]


FROM node:alpine

WORKDIR '/app'

COPY package.json /app
RUN npm config set unsafe-perm true
RUN npm install 

COPY . /app

RUN chown -R node /app/node_modules

USER node

CMD ["npm", "run", "start"]